# -*- coding: utf8 -*-
"""demo test case
"""
#2020/06/30 auto generated by shoots

from toutiaolib.testcase import ToutiaoTest
from toutiaolib.app import ToutiaoApp
from toutiaolib.main import MainWindow

class DemoTest(ToutiaoTest):
    """demo test case
    """
    #owner = "lijingyu.mogu"
    owner = "tanjianxin"
    timeout = 300
    
    def run_test(self):
        self.start_step("start app")
        self.device = self.acquire_device()
        self.app = ToutiaoApp(self.device)
        
        self.start_step("check window")
        window = MainWindow(root=self.app)
        window.wait_for_existing()
        
    
if __name__ == '__main__':
    DemoTest().debug_run()

