# -*- coding: utf8 -*-
#2020/07/02 auto generated by shoots

from shoots_ios.app import iOSApp

class XiguaApp(iOSApp):
    app_spec = {
        "bundle_id": "com.ss.iphone.InHouse.article.Video",
        "kill_process": True
    }
