# -*- coding: utf8 -*-
"""Scroll To Next Room
"""
# 2020/07/02 auto generated by shoots

from xigualib.testcase import XiguaTest
from xigualib.app import XiguaApp
from xigualib.main import MainWindow
import time

class ScrollToNextRoom(XiguaTest):
    """Scroll To Next Room
    """
    #owner = "lijingyu.mogu"
    owner = "tanjianxin"
    timeout = 1000

    def run_test(self):
        self.start_step("start app")
        self.device = self.acquire_device()
        self.app = XiguaApp(self.device)

        #检测启动app是否成功

        self.start_step("check window")
        window = MainWindow(root=self.app)
        window.wait_for_existing()
        # window.init()

        self.start_step("enter room")
        self.assert_("未成功进房", window.EnterRoom() == 0)
        window.SwipeToNextRoom()
        time.sleep(20)

        self.start_step("swipe to next room")
        flag = window.ScrollToNextRoom()
        self.assert_("未成功上下滑", flag == 0)


if __name__ == '__main__':
    ScrollToNextRoom().debug_run()

