# -*- coding: utf8 -*-
"""watching living case
"""
# 2020/07/02 auto generated by shoots

from xigualib.testcase import XiguaTest
from xigualib.app import XiguaApp
from xigualib.main import MainWindow
import time

class WatchingLiving(XiguaTest):
    """watching living case
    """
    # owner = "lijingyu.mogu"
    owner = "tanjianxin"
    timeout = 1000

    def run_test(self):
        self.start_step("start app")
        self.device = self.acquire_device()
        self.app = XiguaApp(self.device)

        self.start_step("check window")
        window = MainWindow(root=self.app)
        window.wait_for_existing()
        # window.init()

        self.start_step("enter room")
        self.assert_("未成功进房", window.EnterRoom() == 0)
        time.sleep(6)
        window.SwipeToNextRoom()
        time.sleep(20)
        window.SwipeToNextRoom()
        time.sleep(20)

        self.start_step("quit room")
        window.QuitRoom()

        self.assert_("未成功退房", window.QuitRoomSuccess() == 0)


if __name__ == '__main__':
    WatchingLiving().debug_run()

