# -*- coding: utf8 -*-
#2020/06/15 auto generated by shoots

from shoots_ios.app import iOSApp

class DouyinApp(iOSApp):
    app_spec = {
        "bundle_id": "com.ss.iphone.ugc.AwemeInhouse",
        "kill_process": True
    }
    system_popup_rules = [
        {
            "match": {"label": "想要访问你的通讯录"},
            "popup_params": {"button_texts": ["启用相机访问权限","启用麦克风访问权限"]}
        }
    ]

