# -*- coding: utf8 -*-
"""test case base
"""
#2020/07/02 auto generated by shoots

from shoots_ios.testcase import iOSTestBase

class XiguaTest(iOSTestBase):
    """xigua test case base
    """
    pass
