# -*- coding: utf8 -*-
"""send gift case
"""
#2020/06/15 auto generated by shoots

from douyinlib.testcase import DouyinTest
from douyinlib.app import DouyinApp
from douyinlib.main import MainWindow
import time
import json

class AnchorSendGift(DouyinTest):
    """send gift case
    """
    #owner = "lijingyu.mogu"
    owner = "tanjianxin"
    timeout = 1000

    def run_test(self):
        self.start_step("start app")
        self.device = self.acquire_device()
        self.app = DouyinApp(self.device)

        self.start_step("check window")
        window = MainWindow(root=self.app)

        time.sleep(2)
        window.init()
        time.sleep(5)

        self.start_step("log in")
        num = window.log_in()

        time.sleep(20)

        self.start_step("start living")
        window.StartLiving()
        time.sleep(3)
        self.assert_("未成功开播", window.StartLivingSuccess() == 0)
        time.sleep(5)

        self.start_step("送礼")
        window.SendGift()
        time.sleep(10)

        self.start_step("close living")
        window.CloseLiving()
        time.sleep(15)
        self.assert_("未成功关播", window.CloseLivingSuccessful() == 0)

        self.start_step("log out")
        window.log_out(num)


if __name__ == '__main__':
    AnchorSendGift().debug_run()
