# -*- coding: utf8 -*-
#2020/06/30 auto generated by shoots

from shoots_ios.app import iOSApp

class ToutiaoApp(iOSApp):
    app_spec = {
        "bundle_id": "com.ss.iphone.InHouse.article.News",
        "kill_process": True
    }
