# -*- coding: utf8 -*-
"""demo test case
"""
#2020/07/02 auto generated by shoots

from xigualib.testcase import XiguaTest
from xigualib.app import XiguaApp
from xigualib.main import MainWindow

class DemoTest(XiguaTest):
    """demo test case
    """
    #owner = "lijingyu.mogu"
    owner = "tanjianxin"
    timeout = 300
    
    def run_test(self):
        self.start_step("start app")
        self.device = self.acquire_device()
        self.app = XiguaApp(self.device)
        
        self.start_step("check window")
        window = MainWindow(root=self.app)
        window.wait_for_existing()

        window.EnterRoom()
        
    
if __name__ == '__main__':
    DemoTest().debug_run()

