"""start living
"""
# 2020/07/02 auto generated by shoots

from xigualib.testcase import XiguaTest
from xigualib.app import XiguaApp
from xigualib.main import MainWindow
import time

class StartLiving(XiguaTest):
    """start living
    """
    #owner = "lijingyu.mogu"
    owner = "tanjianxin"
    timeout = 1000

    def run_test(self):
        self.start_step("start app")
        self.device = self.acquire_device()
        self.app = XiguaApp(self.device)

        self.start_step("check window")
        window = MainWindow(root=self.app)
        window.wait_for_existing()
        # window.init()

        self.start_step("log in")
        num = window.log_in(self.device)
        time.sleep(6)

        self.start_step("start living")
        window.StartLiving()
        time.sleep(6)
        self.assert_("未成功开播", window.StartLivingSuccess() == 0)

        self.start_step("close living")
        window.CloseLiving()
        time.sleep(6)
        self.assert_("未成功关播", window.CloseLivingSuccessful() == 0)

        # self.start_step("log out")
        # window.log_out(num,self.device)
        # time.sleep(6)

if __name__ == '__main__':
    StartLiving().debug_run()