# -*- coding: utf8 -*-
# 2020/06/30 auto generated by shoots

from shoots_android.androidapp import AndroidApp


class DouyinAndroidApps(AndroidApp):
    app_spec = {
        "package_name": "com.ss.android.ugc.aweme",  # app package name
        "init_device": True,  # whether to wake up device
        "process_name": "",  # main process name of app
        "start_activity": "com.ss.android.ugc.aweme.splash.SplashActivity",  # start activity
        "grant_all_permissions": True,  # grant all permissions before starting app
        "clear_data": False,  # pm clear app data
        "kill_process": True  # whether to kill previously started app
    }


class XiguaAndroidApps(AndroidApp):
    app_spec = {
        "package_name": "com.ss.android.article.video",  # app package name
        "init_device": True,  # whether to wake up device
        "process_name": "",  # main process name of app
        "start_activity": "com.ss.android.article.video.activity.SplashActivity",  # start activity
        "grant_all_permissions": True,  # grant all permissions before starting app
        "clear_data": False,  # pm clear app data
        "kill_process": True  # whether to kill previously started app
    }


class HuoshanAndroidApps(AndroidApp):
    app_spec = {
        "package_name": "com.ss.android.ugc.live",  # app package name
        "init_device": True,  # whether to wake up device
        "process_name": "",  # main process name of app
        "start_activity": "com.ss.android.ugc.live.main.MainActivity",  # start activity
        "grant_all_permissions": True,  # grant all permissions before starting app
        "clear_data": False,  # pm clear app data
        "kill_process": True  # whether to kill previously started app
    }


class PipixiaAndroidApps(AndroidApp):
    app_spec = {
        "package_name": "com.sup.android.superb",  # app package name
        "init_device": True,  # whether to wake up device
        "process_name": "",  # main process name of app
        "start_activity": "com.sup.android.base.MainActivity",  # start activity
        "grant_all_permissions": True,  # grant all permissions before starting app
        "clear_data": False,  # pm clear app data
        "kill_process": True  # whether to kill previously started app
    }


class DouyuAndroidApps(AndroidApp):
    app_spec = {
        "package_name": "air.tv.douyu.android",  # app package name
        "init_device": True,  # whether to wake up device
        "process_name": "",  # main process name of app
        "start_activity": "com.douyu.module.home.pages.main.MainActivity",  # start activity
        "grant_all_permissions": True,  # grant all permissions before starting app
        "clear_data": False,  # pm clear app data
        "kill_process": True  # whether to kill previously started app
    }


class HuajiaoAndroidApps(AndroidApp):
    app_spec = {
        "package_name": "com.huajiao",  # app package name
        "init_device": True,  # whether to wake up device
        "process_name": "",  # main process name of app
        "start_activity": "com.huajiao.cover.CoverActivity",  # start activity
        "grant_all_permissions": True,  # grant all permissions before starting app
        "clear_data": False,  # pm clear app data
        "kill_process": True  # whether to kill previously started app
    }


class YYAndroidApps(AndroidApp):
    app_spec = {
        "package_name": "com.duowan.mobile",  # app package name
        "init_device": True,  # whether to wake up device
        "process_name": "",  # main process name of app
        "start_activity": "com.yy.mobile.plugin.homepage.ui.home.HomeActivity",  # start activity
        "grant_all_permissions": True,  # grant all permissions before starting app
        "clear_data": False,  # pm clear app data
        "kill_process": True  # whether to kill previously started app
    }


class YingkeAndroidApps(AndroidApp):
    app_spec = {
        "package_name": "com.meelive.ingkee",  # app package name
        "init_device": True,  # whether to wake up device
        "process_name": "",  # main process name of app
        "start_activity": "com.meelive.ingkee.launcher.ui.IngkeeLauncher",  # start activity
        "grant_all_permissions": True,  # grant all permissions before starting app
        "clear_data": False,  # pm clear app data
        "kill_process": True  # whether to kill previously started app
    }


class KuaishouAndroidApps(AndroidApp):
    app_spec = {
        "package_name": "com.smile.gifmaker",  # app package name
        "init_device": True,  # whether to wake up device
        "process_name": "",  # main process name of app
        "start_activity": "com.yxcorp.gifshow.HomeActivity",  # start activity
        "grant_all_permissions": True,  # grant all permissions before starting app
        "clear_data": False,  # pm clear app data
        "kill_process": True  # whether to kill previously started app
    }
