# -*- coding: utf8 -*-
"""main page
"""
# 2020/06/30 auto generated by shoots
import time
from shoots_android.control import Window
from shoots_android.control import Button, Control, ScrollView, LinearLayout, FrameLayout, RelativeLayout
from uibase.upath import UPath, id_, type_, text_, desc_
from android_device import logger


class StartWindow(Window):
    """start window
    """
    window_spec = {"activity": "com.ss.android.ugc.aweme.splash.SplashActivity"}

    def get_locators(self):
        return {
            "页面": {"type": ScrollView, "path": UPath(id_ == "content", index=0)},
            "首页": {"type": Control, "path": UPath(text_ == "首页")},
            "同城": {"type": Control, "path": UPath(text_ == "同城")},
            "拍摄按钮": {"type": Control, "path": UPath(id_ == "tab_refresh", desc_ == "拍摄，按钮")},
            "消息": {"type": Control, "path": UPath(text_ == "消息")},
            "我": {"type": Control, "path": UPath(text_ == "我")},
            #   直接从Live中进入直播间
            "LIVE": {"type": Control, "path": UPath(id_ == "iv_btn_story_switch")},
            #   可以单击主播头像进入直播间
            "用户头像": {"type": Control, "path": UPath(id_ == "user_avatar")},
            # 初始化
            "个人信息保护指引": {"type": Control, "path": UPath(id_ == "title", text_ == "个人信息保护指引")},
            "好的": {"type": Control, "path": UPath(id_ == "confirm", text_ == "好的")},
            "我知道了": {"type": Control, "path": UPath(id_ == "tv_right", text_ == "我知道了")},
            "设置": {"type": Control, "path": UPath(id_ == "more_btn")},
            "DebugTest": {"type": Control, "path": UPath(text_ == "Debug Test")},
            "设置页的设置": {"type": Control, "path": UPath(text_ == "设置")},
            "发现通讯录好友": {"type": Control, "path": UPath(id_ == "title", text_ == "发现通讯录好友")},
            "取消": {"type": Control, "path": UPath(id_ == "cancel", text_ == "取消")},
            "进入儿童/青少年模式": {"type": Control, "path": UPath(text_ == "进入儿童/青少年模式")},
            "好友推荐": {"type": Control, "path": UPath(id_ == "title_recommend_user", text_ == "好友推荐")},
            "好友推荐关闭": {"type": Control, "path": UPath(id_ == "close")},
            "上滑查看更多视频": {"type": Control, "path": UPath(id_ == "tv_strengthen_swipe_up_guide", text_ == "上滑查看更多视频")},
            "长按屏幕使用更多功能": {"type": Control, "path": UPath(id_ == "long_click_guide_title", text_ == "长按屏幕使用更多功能")},
            "不感兴趣": {"type": Control, "path": UPath(text_ == "不感兴趣")},
            "直播": {"type": Control, "path": UPath(id_ == "live_square_entrance_img")},
            "通知，是件很重要的事情": {"type": Control, "path": UPath(id_ == "tv_title", text_ == "通知，是件很重要的事情")},
            "稍后": {"type": Control, "path": UPath(id_ == "tv_left", text_ == "稍后")},
            "检测到更新": {"type": Control, "path": UPath(id_ == "title_text", text_ == "检测到更新")},
            "以后再说": {"type": Control, "path": UPath(id_ == "later_btn", text_ == "以后再说")},
            "关注": {"type": LinearLayout, "path": UPath(id_ == "following_layout", index=0)},
        }

    def wait_for_loading(self):
        self['页面'].wait_for_visible()

    def init(self, device):
        if self["通知，是件很重要的事情"].existing:
            if self["通知，是件很重要的事情"].visible:
                logger.info("通知，是件很重要的事情")
                self["稍后"].click()

        if self["个人信息保护指引"].existing:
            if self["个人信息保护指引"].visible:
                logger.info("个人信息")
                self["好的"].click()

        if self["发现通讯录好友"].existing:
            if self["发现通讯录好友"].visible:
                logger.info("个人通讯录信息")
                self["取消"].click()

        if self["进入儿童/青少年模式"].existing:
            if self["进入儿童/青少年模式"].visible:
                logger.info("青少年模式")
                self["我知道了"].click()

        if self["好友推荐"].existing:
            if self["好友推荐"].visible:
                logger.info("好友推荐")
                self["好友推荐关闭"].click()

        if self["上滑查看更多视频"].existing:
            if self["上滑查看更多视频"].visible:
                logger.info("上滑")
                device._driver.adb.shell_command("input swipe %s %s %s %s" % (
                    device.screen_rect.width // 2, device.screen_rect.height // 2,
                    device.screen_rect.width // 2, device.screen_rect.height // 20))

        time.sleep(2)

        if self["检测到更新"].existing:
            if self["以后再说"].visible:
                print("检测到更新")
                self["以后再说"].click()

        if self["长按屏幕使用更多功能"].existing:
            if self["长按屏幕使用更多功能"].visible:
                logger.info("长按")
                device._driver.adb.shell_command(
                    "input tap %s %s" % (device.screen_rect.width // 2, device.screen_rect.height // 3))

    def open_me_page(self):
        """打开「我」页面"""
        self["我"].click()
        try:
            self["关注"].wait_for_visible()
        except:
            time.sleep(2)
            self["我"].click()
            self["关注"].wait_for_visible()
        time.sleep(1)

    def open_follow_page(self):
        """点开关注列表页面"""
        try:
            self["关注"].click()
        except:
            time.sleep(3)
            self["关注"].click()
