# -*- coding: utf8 -*-
"""test case base
"""
# 2020/07/07 auto generated by shoots

from shoots_android.androidtestbase import AndroidTestBase


class DouyinAndroidTest(AndroidTestBase):
    """douyin4206 test case base
    """
    pass
