# -*- coding: utf8 -*-
"""project settings file
"""
#2020/06/30 auto generated by shoots

import os

PROJECT_NAME = "douyin4206"
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
INSTALLED_LIBS = ["uibase", "shoots_android"]
