# -*- coding: utf8 -*-
"""test plan demo
"""
#2020/07/02 auto generated by shoots

from shoots.plan import TestPlan

class DemoTestPlan(TestPlan):
    """xigua demo plan
    """
    tests = "xiguatest.demo.DemoTest"
    
if __name__ == "__main__":
    DemoTestPlan().debug_run()
