# -*- coding: utf8 -*-
"""test case base
"""
#2020/06/30 auto generated by shoots

from shoots_ios.testcase import iOSTestBase

class ToutiaoTest(iOSTestBase):
    """toutiao test case base
    """
    pass
