from selenium import webdriver
import time
from collections import Counter

driver=webdriver.Chrome()
time.sleep(1)
driver.maximize_window()
time.sleep(1)
driver.get("http://172.16.20.151")
time.sleep(1)
driver.find_element_by_name("uname").send_keys("superadmin")
time.sleep(1)
driver.find_element_by_name("pass").send_keys("superadmin")
driver.find_element_by_xpath("//*[@id='login_form']/div[4]/div/button").click()
time.sleep(5)
driver.find_element_by_name("device").click()
time.sleep(1)
driver.find_element_by_name("devicemanage").click()
time.sleep(2)
checkbox = driver.find_elements_by_class_name("el-checkbox")
checkbox[1].click()
time.sleep(1)
driver.find_element_by_name("sendBtn").click()
time.sleep(4)
driver.find_element_by_name("sendDownBtn").click()
time.sleep(2)
driver.find_element_by_name("deviceSN").clear()
time.sleep(1)
driver.find_element_by_name("deviceSN").send_keys("FC241118370049")
time.sleep(1)
button_list1 = driver.find_elements_by_name("searchBtn")
button_list1[1].click()
time.sleep(2)
#下发设备配置到另外一台设备
driver.find_element_by_name("deviceSN").click()
time.sleep(1)
driver.find_element_by_name("deviceSN").clear()
time.sleep(1)
button_num=driver.find_elements_by_name("searchBtn")
button_num[1].click()
time.sleep(2)

