# -*- coding: utf8 -*-
"""test plan demo
"""
#2020/06/28 auto generated by shoots

from shoots.plan import TestPlan

class DemoTestPlan(TestPlan):
    """huoshan demo plan
    """
    tests = "huoshantest.demo.DemoTest"
    
if __name__ == "__main__":
    DemoTestPlan().debug_run()
