# -*- coding: utf8 -*-
"""OkPop page
"""
#2020/06/15 auto generated by shoots

from uibase.controls import Window
from uibase.upath import UPath, text_, type_, label_, id_
import time
from webcastlib.mobile_account import MobileRequest
from douyinlib.LoginWindow import LoginWindow
from shoots import logger

class OkPopup(Window):
    """OkPopup window
    """
    window_spec = {"path": UPath(type_ == "UIWindow")}

    def get_locators(self):
        return {
            "确认": {"path": UPath(label_ == "确认", id_ == "(actionContentView)",index=0)},
            "确认1": {"path": UPath(label_ == "确认", id_ == "(label)",type_=="UILabel",index=0)}#确认退出新样式
        }

    def logout(self):
        if self["确认1"].wait_for_visible(raise_error=False):
            self["确认1"].click()
            print("点击确认1")

        else:
            self["确认"].click()
        time.sleep(3)
