# -*- coding: utf8 -*-
"""test case base
"""
#2020/06/15 auto generated by shoots

from shoots_ios.testcase import iOSTestBase

class DouyinTest(iOSTestBase):
    """douyin test case base
    """
    pass

