# -*- coding: utf8 -*-
"""project settings file
"""
#2020/06/15 auto generated by shoots

import os

PROJECT_NAME = "webcast_qa"
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
INSTALLED_LIBS = ["uibase", "shoots_ios"]
SHOOTS_POPUP_CLASSES = ["douyinlib.popup.IknowPopup",
                        "douyinlib.popup.PersonalInformationPopup",
                        "douyinlib.popup.FindFriendsPopup","douyinlib.popup.LocationPopup",
                        "douyinlib.popup.MoreLivePopup",
                        "huoshanlib.popup.ChildModePop",
                        #"huoshanlib.popup.SwipePopup",
                        "huoshanlib.popup.OuterTestPop",
                        "huoshanlib.popup.CloseLivePopup",
                        "huoshanlib.popup.BetaTestPop",
                        "huoshanlib.popup.PrivacyAlertPop",
                        "huoshanlib.popup.FollowGuidePopup",
                        "huoshanlib.popup.PersonalInformationPopup", "huoshanlib.popup.FindFriendsPopup",

                        "toutiaolib.popup.GotIt",
                        "toutiaolib.popup.Closeling",
                        "toutiaolib.popup.TTAppUpdateTipView", "toutiaolib.popup.PushPopup",
                        "toutiaolib.popup.PushPopupNew",
                        "toutiaolib.popup.NewPagePopup",
                        "toutiaolib.popup.TestGudiePopup",
                         "xigualib.popup.IknowPopup",
                         "xigualib.popup.IagreePopup",
                         "xigualib.popup.QuitRoom",
                         "xigualib.popup.Morelogin",
                        "xigualib.popup.UseErrorPopup"]
