# -*- coding: utf8 -*-
#2020/06/28 auto generated by shoots

from shoots_ios.app import iOSApp

class HuoshanApp(iOSApp):
    app_spec = {
        "bundle_id": "com.ss.iphone.ugc.LiveInhouse",
        "kill_process": True
    }
