# -*- coding: utf8 -*-
"""test case base
"""
#2020/06/28 auto generated by shoots

from shoots_ios.testcase import iOSTestBase

class HuoshanTest(iOSTestBase):
    """huoshan test case base
    """
    pass
